"""pages table

Revision ID: b0cd8231c69d
Revises: 
Create Date: 2018-09-09 20:21:44.512946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cd8231c69d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_json'), 'page', ['json'], unique=True)
    op.create_index(op.f('ix_page_url'), 'page', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_url'), table_name='page')
    op.drop_index(op.f('ix_page_json'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
